[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }

[environments.production.serviceConnect]
allowPublicNetworking = true

# Railway automatically handles:
# - PORT environment variable
# - HTTPS/SSL certificates
# - Domain management
# - Auto-scaling
# - Zero-downtime deployments

# Note: No healthcheck configuration as per requirements
